# Generated by Django 5.1.1 on 2024-10-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excercisecategory',
            name='category',
            field=models.CharField(choices=[('Beginner1', 'Beginner 1'), ('Beginner2', 'Beginner 2'), ('Functional_Endurance1', 'Functional Endurance 1'), ('Functional_Endurance2', 'Functional Endurance 2'), ('Functional_Endurance3', 'Functional Endurance 3'), ('Strength', 'Strength'), ('Power', 'Power'), ('Med_ball_core', 'Med Ball Core'), ('Med_ball_power', 'Med Ball Power'), ('Core_hip_legs', 'Core Hip/Legs'), ('Thoracic_spine_mobility', 'Thoracic Spine Mobility'), ('Scapular_closed_chain', 'Scapular Closed Chain'), ('Scapular_open_chain', 'Scapular Open Chain'), ('Scapulo_thoracic', 'Scapulo Thoracic'), ('Scapulo_thoracic_hip', 'Scapulo Thoracic Hip'), ('Active_wrist_mobilization', 'Active Wrist Mobilization'), ('Agility_ladder', 'Agility Ladder'), ('Cone_drills', 'Cone Drills'), ('General_strength', 'General Strength'), ('General_mobility', 'General Mobility'), ('Kettlebell_training', 'Kettlebell Training'), ('Hops_and_bounds', 'Hops and Bounds'), ('Lower_leg', 'Lower Leg'), ('Leg_stable', '1 Leg Stable'), ('Leg_stable_unstable', '1 Leg Stable/2 Leg Unstable'), ('Leg_unstable', '2 Leg Unstable/1 Leg Unstable'), ('Stabilization_1', 'Stabilization 1'), ('Stabilization_2', 'Stabilization 2'), ('Shoulders', 'Shoulders'), ('Rear_shoulders', 'Rear_shoulders'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Compound', 'Compound'), ('Shoulders_strength', 'Shoulders_strength'), ('Rear_delts_strength', 'Rear_delts_strength')], max_length=255),
        ),
        migrations.AlterField(
            model_name='excercisecategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
